apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cloud-api
spec:
  hosts:
  - cloud-api
  http:
  - match:
    - uri:
        prefix: /v2/
    route:
    - destination:
        host: cloud-api
        subset: v2
      weight: 90
    - destination:
        host: cloud-api
        subset: v2-canary
      weight: 10
  - route:
    - destination:
        host: cloud-api
        subset: v1
